# Generated by Django 5.2.11 on 2026-02-17 16:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('PROGRESS', 'In Progress'), ('X_WON', 'X Won'), ('O_WON', 'O Won'), ('DRAW', 'Draw')], default='PROGRESS', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Square',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('claimed_by', models.CharField(blank=True, max_length=1)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squares', to='game.game')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('game', 'position')},
            },
        ),
        migrations.CreateModel(
            name='SubSquare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('claimed_by', models.CharField(blank=True, max_length=1)),
                ('square', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_squares', to='game.square')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('square', 'position')},
            },
        ),
    ]
